### ISSUE TITLE
Request to add "dunder" to Python culture page

### ISSUE THREAD

**Issue by Aramgutang** [pyconau/2023-website#30]
I know it's not an in-joke, but participants who are mainly familiar with Python by reading about it, rather than speaking about it, can be unfamiliar with that contraction.

Also, an explanation of "magic" (maybe even mention Django's magic-removal branch), and how in Python the word has negative connotations might be nice to mention in conjunction, since dunders enable magic. That bit would be for beginners.

**Comment by mattcen** [comment]
If we want to do this, this recent talk in dunders is an excellent reference to link to: https://m.youtube.com/watch?v=CSpzTx-S8B0
